#!/usr/bin/env bash

APP_SPECS_FOLDER=$1
DEST_APP_FOLDER=$2

SCRIPT=$(readlink -f $0)
SCRIPTPATH=`dirname $SCRIPT`

TEMPLATE_DIR=${SCRIPTPATH}/Template

echo 'Copy template into app directory'
cp -r ${TEMPLATE_DIR}/* $DEST_APP_FOLDER

touch ${TMPDIR}/bak
sed -i ${TMPDIR}/bak -e s/"WebShell 0.9.6"/"WebShell (build ${TDDIUM_SESSION_ID})"/g ${DEST_APP_FOLDER}/WebShell/www/webshell.html

echo 'Copy generated AppSpecs files'
cp -r ${APP_SPECS_FOLDER}/* ${DEST_APP_FOLDER}

echo 'Done'
